substitutions:
  mic_gain_factor: "3"
  va_auto_gain: "15dBFS"
  va_noise_suppression: "1"
  va_volume_multiplier: "2.5"

esphome:
  name: voice-assistant-esp32
  friendly_name: Voice Assistant ESP32

  on_boot:
    priority: 200
    then:
      - delay: 10s
      - micro_wake_word.start


esp32:
  board: esp32dev
  framework:
    type: esp-idf


logger:
  level: DEBUG


api:
  encryption:
    key: !secret api_encryption_key


ota:
  password: !secret ota_password


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  power_save_mode: NONE
  fast_connect: true

  # Fallback access point (recovery mode)
  ap:
    ssid: "ESP32-Voice-Recovery"
    password: !secret fallback_password


web_server:
  port: 80


# =========================
# STATUS LED (optional)
# =========================
output:
  - platform: gpio
    pin: GPIO2
    id: status_led_output


light:
  - platform: binary
    name: "Status LED"
    output: status_led_output
    id: status_led


# =========================
# I2S BUS
# =========================
i2s_audio:
  - id: i2s_bus
    i2s_lrclk_pin: GPIO27
    i2s_bclk_pin: GPIO14


# =========================
# INMP441 MICROPHONE
# =========================
microphone:
  - platform: i2s_audio
    id: mic
    adc_type: external

    i2s_din_pin: GPIO33
    channel: left

    i2s_audio_id: i2s_bus
    sample_rate: 16000


# =========================
# WAKE WORD
# =========================
micro_wake_word:
  models:
    - model: hey_jarvis
      probability_cutoff: 0.7

  microphone:
    microphone: mic
    gain_factor: ${mic_gain_factor}

  on_wake_word_detected:
    - voice_assistant.start


# =========================
# VOICE ASSISTANT
# =========================
voice_assistant:
  id: assistant
  microphone: mic
  use_wake_word: true

  auto_gain: ${va_auto_gain}
  noise_suppression_level: ${va_noise_suppression}
  volume_multiplier: ${va_volume_multiplier}

  on_listening:
    - light.turn_on: status_led

  on_end:
    - light.turn_off: status_led
    - wait_until:
        not: voice_assistant.is_running
    - micro_wake_word.start

  on_error:
    - light.turn_off: status_led
    - voice_assistant.stop
    - micro_wake_word.start


# =========================
# DEBUG INFO
# =========================
text_sensor:

  - platform: wifi_info
    ip_address:
      name: "ESP32 IP Address"

  - platform: template
    name: "Voice Assistant State"
    lambda: |-
      if (id(assistant).is_running()) {
        return {"Listening..."};
      } else {
        return {"Idle (Wake word active)"};
      }
    update_interval: 1s
